name: Build mod_manager

permissions:
  contents: write

on:
  push:
    branches:
      - latest

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        py -m nuitka main.py --standalone --onefile --windows-console-mode=disable --enable-plugin=pyqt6 --include-data-files=app_icon.ico=app_icon.ico --include-data-files=default.png=default.png --include-data-files=UnRAR.exe=UnRAR.exe --windows-icon-from-ico=app_icon.ico --output-filename=HD2MM.exe

    - id: get_version
      run: |
        import os, yaml
        
        with open('info.yml', 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)
        
        version = data['version']
        log = data.get('log', '')

        log_lines = log.splitlines()
        formatted_log = '\n'.join(f"- {line}" for line in log_lines)
        
        with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='utf-8') as fh:
            print(f"version={version}", file=fh)
            print(f"log<<EOF", file=fh)
            print(formatted_log, file=fh)
            print("EOF", file=fh)
      shell: python

    - name: Create Release and upload assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: Release ${{ steps.get_version.outputs.version }}
        body: |
          ${{ steps.get_version.outputs.version }}
          更新内容:
          ${{ steps.get_version.outputs.log }}
        files: ./HD2MM.exe
        update: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
